DEFINITIONS = {
    "Page title": "The title of the web page",
    "Publication title": "The title of the downloadable output or publication",
    "File name": "The name of the specific output or publication file",
    "Link": "URL or file path to access the content",
    "File type": "The type of file (e.g. PDF, DOCX, XLSX)",
    "Content type": "The category of content (e.g. Publication, Comment, Explainer, Event)",
    "Publication type": "The specific type of publication (e.g. Report, Analysis paper, Insight paper)",
    "Published date": "The date when the content was first published",
    "Updated date": "The date when the content was last updated, as recorded in the 'Last update' field in the CMS",
    "Team": "The IfG team responsible for the content",
    "Author": "The author(s) of the content",
    "Topic": "The policy area or subject matter covered",
    "Pages": "The number of distinct pages included in the data",
    "Page views": "Every time a page is loaded or reloaded in a browser",
    "Active users": "The number of unique users who have interacted with the site",
    "Page views per active user": "The average number of pages viewed by each active user",
    "Average engagement time per active user": "The average time spent on the site by each active user",
    "Downloads": "The number of times a file has been downloaded",
    "Download rate": "The percentage of page views that resulted in a download",
}
